hostapd: qcwcn BOARD_HOSTAPD_PRIVATE_LIB has its own namespace now
This patch fixes the following hostapd build failure because
Qcom qcwcn hostapd private library has its own namespace now:

  FAILED: out/soong/build.db845c.ninja
  error: external/wpa_supplicant_8/hostapd/Android.bp:645:1: "hostapd" depends on undefined module "lib_driver_cmd_qcwcn".
  Module "hostapd" is defined in namespace "." which can read these 1 namespaces: ["."]
  Module "lib_driver_cmd_qcwcn" can be found in these namespaces: ["hardware/qcom/wlan/wcn6740"]
  14:42:52 soong bootstrap failed with: exit status 1

Change-Id: I394591ddbad430b45712216452a79fbce0407ab8
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>