dragonboards: Switch to bootcontrol AIDL HAL
Otherwise we run into following build failures, with
"API_LEVEL := 34", on linaro_swr-userdebug and
sm8x50-userdebug build targets:

  ERROR: files are incompatible: \
  android.hardware.boot@1.2::IBootControl/default is \
  deprecated in compatibility matrix at FCM Version 8; \
  it should not be served.

Test: Build sm8x50-trunk_staging-userdebug or linaro_swr-trunk_staging-userdebug
Fixes: 719682a4189f (Re-apply "db845c: upgrade PRODUCT_SHIPPING_API_LEVEL to 34")
Change-Id: Ia989ce3272f7a2127bae0848a698c3b3f680bb39
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
[jstultz: Cherrypicked from
 https://android-review.googlesource.com/c/device/linaro/dragonboard/+/3571866 ]
Signed-off-by: John Stultz <jstultz@google.com>