db845c-userdebug: Enable generic Thermal and Power AIDL HALs from vendor-package
Set `TARGET_USES_LIBPM=true` at build time to enable generic
Thermal and Power AIDL HALs from libpm project.

For now this HAL is only tested on DB845c *and not on RB5*.

These HAL source files are shipped in the latest vendor-package
version (20250311). `TARGET_USES_LIBPM=true` will puposely
break the builds using an older vendor-package version.

  device/linaro/dragonboard/db845c/device.mk:70: \
    error:  vendor/linaro/shared/20250311/external/libpm/device.mk does not exist..

Platform specific thermal configuration is picked-up from the
/vendor/etc/thermal-`getProperty(vendor.thermal.config)`.json
file. If platform thermal config file is not found then it
will fallback to a default thermal config file, thermal.json,
which may or maynot work. So it is advisable to prepare device
specific thermal config file before enabling this HAL.

AOSP fork for the upstream libpm.git project is hosted at
https://source.devboardsforandroid.linaro.org/platform/external/libpm/+log/refs/heads/d4a

Change-Id: Ie3b08f92e402eb828698421ceb92518b0d72999b
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>