dragonboards: Set FORCE_USE_ANDROIDMK_FOR_WPA_CONF
Otherwise build will fail because of missing Android.bp
in hardware/qcom/wlan/legacy/qcwcn/ project:

  In file included from hardware/qcom/wlan/legacy/qcwcn/config/Android.mk:22:
  external/wpa_supplicant_8/wpa_supplicant/wpa_supplicant_conf.mk:13: \
    error: wpa_supplicant.conf already converted to soong, \
    do not include wpa_supplicant_conf.mk in Android.mk. \
    Instead replace it with Android.bp, for example in \
    hardware/broadcom/wlan/bcmdhd/config/Android.bp or \
    add 'FORCE_USE_ANDROIDMK_FOR_WPA_CONF := true' to your product config.
  ckati failed with: exit status 1

Also fixed a relevant Selinux denial.

Bug: 428068529
Change-Id: I63653b110835b03ff589879bf23625f695b456cf
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>